[project]
name = "chatbotcli"
version = "1.0.2"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Ashwin Panchal", email = "ashwinpanchal.iitb@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "openai>=3.13.0",
    "pydantic>=2.13.5",
    "pydantic-settings>=2.15.0",
]

[project.scripts]
chatbotcli = "chatbotcli:main"

[build-system]
requires = ["uv_build>=0.12.13,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest>=9.1.1",
]
